# Generated by Django 3.2.15 on 2022-09-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact_number', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_of_joining', models.DateTimeField(default=django.utils.timezone.now)),
                ('residental_address', models.CharField(blank=True, max_length=150)),
                ('office_college_address', models.CharField(blank=True, max_length=300)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('monthly_rent', models.IntegerField(blank=True, null=True)),
                ('security_amount', models.IntegerField(blank=True, null=True)),
                ('id_proof_document_name', models.CharField(blank=True, max_length=30)),
                ('id_proof_document', models.ImageField(blank=True, upload_to='documents_pics')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user_room_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
