# Generated by Django 3.2.15 on 2022-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_month_pay_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
