# Generated by Django 3.2.15 on 2022-09-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(null=True)),
                ('room_type', models.CharField(max_length=50)),
                ('room_status', models.CharField(max_length=50)),
                ('check_in_date', models.DateField(null=True)),
                ('room_for', models.CharField(max_length=50)),
                ('room_floor', models.CharField(blank=True, max_length=50)),
                ('room_user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Room_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room_management.room_management')),
                ('room_user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
