# Generated by Django 3.2.15 on 2022-09-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_title', models.CharField(max_length=100)),
                ('complain_description', models.TextField()),
                ('complain_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default_food.jpg', upload_to='complain_pic')),
                ('complain_type', models.CharField(max_length=50)),
                ('user_complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
